### ISSUE TITLE
Hello Isaac 

### ISSUE THREAD

**Issue by Temian1** [mina-isaac-99/directions#1]
Would like to ask
When will you add the admin panel and moderators and chat system

Will there be karma implementation

**Comment by aziz-mina** [comment]
👋 Hello , [Temian1](https://github.com/Temian1) 
I'm working now on admin panel , moderators and chat .
Sorry , not sure about karma , but I'll try

**Comment by Temian1** [comment]
> 👋 Hello , [Temian1](https://github.com/Temian1) I'm working now on admin panel , moderators and chat . Sorry , not sure about karma , but I'll try


That's nice  will be checking ☺️
